### ISSUE TITLE
Add WCH CH569 parameter to change RDPR USER_MEM

### ISSUE THREAD

**Issue by bvernoux** [hydrausb3/wch-isp#2]
Add setting of user configuration word USER_MEM to be changed to 32KB, 64KB or 96KB

**Comment by bvernoux** [comment]
Add setting of user configuration word USER_MEM to be changed to 32KB, 64KB or 96KB

**Comment by hansfbaier** [comment]
Has this been fixed by https://github.com/hydrausb3/wch-isp/pull/9
or do you mean something else here?

**Comment by bvernoux** [comment]
Yes it is implemented now this issue can be closed as it is available in [release v0.2.0 ](https://github.com/hydrausb3/wch-isp/releases/tag/v0.2.0)
